### PR TITLE
Move from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by marvinschopf**
Hello @ndresx!

I ported the Travis CI workflow to GitHub Actions in this pull request.

Travis now no longer offers unrestricted free builds for open source projects, has become very slow at times and is shutting down their `travis-ci.org` platform in a few weeks. So unfortunately, in my eyes, it is time to leave Travis CI behind and switch to GitHub Actions.

Kind regards
Marvin

### CODE REVIEW

**Comment by ndresx** [comment]
Hi @marvinschopf, thanks for the PR! I will have to look into what you did, so it will take me a while, but I think it'd be cool to also have GitHub Actions, **in addition to Travis CI!**

**Why?** First of all, they are not really shutting down their platform but are migrating it to `travis-ci.com`. This already works today, and also this repo has been migrated to their new environment. And the free build restriction you have mentioned only applies to their Free Plan. Open-Source projects like this will continue to be free, and even if not, the amount of builds we have here on a regular basis is very low anyway.

If you have any news that would state otherwise, please let me know. Last but not least, I would really like to try them out in parallel, just to see if it works, and how it works. So maybe you could just revert the deletion of the `.travis.yml` file please and as said, I'd then at some point take another look at it. Thanks again already for the initiative and your effort though!

**Comment by marvinschopf** [comment]
Hello @ndresx!

I understand your points entirely. Please also excuse that I was not fully informed about the shutdown of Travis. 

I have added the `.travis.yml` again.

**Comment by marvinschopf** [comment]
Hello @ndresx!

I can fully understand your arguments. I took another close look at Travis' status and you are absolutely right. My apologies.

I have added the `.travis.yml` again. It would be really great if both services could be tried in parallel.

**Comment by ndresx** [comment]
This is now merged, thanks again!

**Pull request merged**
